### PR TITLE
Update Wiring&Cabling Notes.txt

### PR DESCRIPTION
**Pull request by MikeeChevalier**
Added colour codes for alternative 4 and 7 conductor cabling

### CODE REVIEW

**Review by Brent-Lekx-Toniolo — COMMENTED** [review]
Which cables are these refering to @MikeeChevalier ?

**Comment by MikeeChevalier** [comment]
#14 4 conductor and #14 7 conductor. There was an issue where we couldn't get the colour scheme as we usually do (all conductors are black and have a number on them, except the last one which is green for ground). We ended up getting wire that was colour coded. It matched up with the Allen Bradley colouring scheme so I made the executive decision to set that as the standard when using this cable. We're back to using the black conductor stuff, but I figured I'd add it again for next time we need to use it.

**Comment by Brent-Lekx-Toniolo** [comment]
OK maybe add a note to the title about what cable it's for, just to avoid confusion with any other four conductor cable (say a sensor cable).....thanks!

**Comment by Brent-Lekx-Toniolo** [comment]
@MikeeChevalier with all the updates you just did to the wiki, is the above still valid? If not can you make note and close the request? Thanks

**Comment by MikeeChevalier** [comment]
Danilo actually decided to scrap all of this wire and get the wire we would normally use, so this never ended up existing. I'll close the request.

**Pull request closed without merging**
